# Generated by Django 5.2 on 2025-04-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_payment_status'),
        ('users', '0003_delete_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, to='main.course'),
        ),
    ]
