# Generated by Django 5.2 on 2025-04-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.URLField(blank=True, null=True),
        ),
    ]
